---
build_from:
  amd64: "ghcr.io/home-assistant/amd64-base-ubuntu:stable"
  aarch64: "ghcr.io/home-assistant/aarch64-base-ubuntu:stable"
  armhf: "ghcr.io/home-assistant/armhf-base-ubuntu:stable"
  armv7: "ghcr.io/home-assistant/armv7-base-ubuntu:stable"
  i386: "ghcr.io/home-assistant/i386-base-ubuntu:stable"
  #aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
  #amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
  #armhf: ghcr.io/hassio-addons/debian-base/armhf:stable
  #armv7: ghcr.io/hassio-addons/debian-base/armv7:stable
  #i386: ghcr.io/hassio-addons/debian-base/i386:stable
codenotary:
  base_image: tdlj@tdlj.net
  signer: tdlj@tdlj.net
