---
name: predai
version: 1.1.12
slug: predai
description: AI Based time series prediction for Home Assistant
url: https://github.com/springfall2008/predai
codenotary: tdlj@tdlj.net
webui: http://[HOST]:[PORT:5052]
arch:
  - aarch64
  - amd64
  - armv7
init: false
homeassistant_api: true
hassio_api: true
hassio_role: admin
auth_api: true
ports_description:
  5052/tcp: PredAI
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
options:
  dummy: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  dummy:
    - str
