---
build_from:
  aarch64: github.com/hassio-addons/addon-ubuntu-base:9.0.4
  amd64: github.com/hassio-addons/addon-ubuntu-base:9.0.4
  armv7: github.com/hassio-addons/addon-ubuntu-base:9.0.4
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
